namespace EarthMarket.DataAccess.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class editedconstraintstothemodels : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.AttributeValues", "Attribute_Key", "dbo.Attributes");
            DropForeignKey("dbo.AttributeValues", "Value_Key", "dbo.Values");
            DropForeignKey("dbo.CartProductVariants", "Cart_Key", "dbo.Carts");
            DropForeignKey("dbo.CartProductVariants", "ProductVariant_Key", "dbo.ProductVariants");
            DropForeignKey("dbo.Carts", "User_Key", "dbo.Users");
            DropForeignKey("dbo.Orders", "User_Key", "dbo.Users");
            DropForeignKey("dbo.OrderProductVariants", "Order_Key", "dbo.Orders");
            DropForeignKey("dbo.OrderProductVariants", "ProductVariant_Key", "dbo.ProductVariants");
            DropForeignKey("dbo.ProductVariants", "Product_Key", "dbo.Products");
            DropForeignKey("dbo.VariantAttributeValues", "ProductVariant_Key", "dbo.ProductVariants");
            DropForeignKey("dbo.ProductVariantImages", "ProductVariant_Key", "dbo.ProductVariants");
            DropForeignKey("dbo.ProductCategories", "Product_Key", "dbo.Products");
            DropForeignKey("dbo.ProductImages", "Product_Key", "dbo.Products");
            DropForeignKey("dbo.ProductCategories", "Category_Key", "dbo.Categories");
            DropForeignKey("dbo.VariantAttributeValues", "AttributeValue_Key", "dbo.AttributeValues");
            DropIndex("dbo.AttributeValues", new[] { "Attribute_Key" });
            DropIndex("dbo.AttributeValues", new[] { "Value_Key" });
            DropIndex("dbo.CartProductVariants", new[] { "Cart_Key" });
            DropIndex("dbo.CartProductVariants", new[] { "ProductVariant_Key" });
            DropIndex("dbo.Carts", new[] { "User_Key" });
            DropIndex("dbo.Orders", new[] { "User_Key" });
            DropIndex("dbo.OrderProductVariants", new[] { "Order_Key" });
            DropIndex("dbo.OrderProductVariants", new[] { "ProductVariant_Key" });
            DropIndex("dbo.ProductVariants", new[] { "Product_Key" });
            DropIndex("dbo.ProductCategories", new[] { "Category_Key" });
            DropIndex("dbo.ProductCategories", new[] { "Product_Key" });
            DropIndex("dbo.ProductImages", new[] { "Product_Key" });
            DropIndex("dbo.VariantAttributeValues", new[] { "AttributeValue_Key" });
            DropIndex("dbo.VariantAttributeValues", new[] { "ProductVariant_Key" });
            DropIndex("dbo.ProductVariantImages", new[] { "ProductVariant_Key" });
            DropIndex("dbo.UserRoles", new[] { "UserKey" });
            DropIndex("dbo.UserRoles", new[] { "RoleKey" });
            AlterColumn("dbo.Attributes", "Name", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.AttributeValues", "Attribute_Key", c => c.Guid(nullable: false));
            AlterColumn("dbo.AttributeValues", "Value_Key", c => c.Guid(nullable: false));
            AlterColumn("dbo.Values", "Name", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.CartProductVariants", "Cart_Key", c => c.Guid(nullable: false));
            AlterColumn("dbo.CartProductVariants", "ProductVariant_Key", c => c.Guid(nullable: false));
            AlterColumn("dbo.Carts", "User_Key", c => c.Guid(nullable: false));
            AlterColumn("dbo.Users", "Name", c => c.String(nullable: false, maxLength: 30));
            AlterColumn("dbo.Users", "Email", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Users", "HashedPassword", c => c.String(nullable: false));
            AlterColumn("dbo.Users", "Salt", c => c.String(nullable: false));
            AlterColumn("dbo.Orders", "User_Key", c => c.Guid(nullable: false));
            AlterColumn("dbo.OrderProductVariants", "Order_Key", c => c.Guid(nullable: false));
            AlterColumn("dbo.OrderProductVariants", "ProductVariant_Key", c => c.Guid(nullable: false));
            AlterColumn("dbo.ProductVariants", "Price", c => c.Double(nullable: false));
            AlterColumn("dbo.ProductVariants", "Product_Key", c => c.Guid(nullable: false));
            AlterColumn("dbo.Products", "Name", c => c.String(nullable: false));
            AlterColumn("dbo.ProductCategories", "Category_Key", c => c.Guid(nullable: false));
            AlterColumn("dbo.ProductCategories", "Product_Key", c => c.Guid(nullable: false));
            AlterColumn("dbo.Categories", "Name", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.ProductImages", "ImagePath", c => c.String(nullable: false));
            AlterColumn("dbo.ProductImages", "Product_Key", c => c.Guid(nullable: false));
            AlterColumn("dbo.VariantAttributeValues", "AttributeValue_Key", c => c.Guid(nullable: false));
            AlterColumn("dbo.VariantAttributeValues", "ProductVariant_Key", c => c.Guid(nullable: false));
            AlterColumn("dbo.ProductVariantImages", "ImagePath", c => c.String(nullable: false));
            AlterColumn("dbo.ProductVariantImages", "ProductVariant_Key", c => c.Guid(nullable: false));
            AlterColumn("dbo.Roles", "Name", c => c.String(nullable: false, maxLength: 20));
            CreateIndex("dbo.Attributes", "Name", unique: true);
            CreateIndex("dbo.AttributeValues", "Attribute_Key");
            CreateIndex("dbo.AttributeValues", "Value_Key");
            CreateIndex("dbo.Values", "Name", unique: true);
            CreateIndex("dbo.CartProductVariants", "Cart_Key");
            CreateIndex("dbo.CartProductVariants", "ProductVariant_Key");
            CreateIndex("dbo.Carts", "User_Key");
            CreateIndex("dbo.Users", "Name", unique: true);
            CreateIndex("dbo.Users", "Email", unique: true);
            CreateIndex("dbo.Orders", "User_Key");
            CreateIndex("dbo.OrderProductVariants", "Order_Key");
            CreateIndex("dbo.OrderProductVariants", "ProductVariant_Key");
            CreateIndex("dbo.ProductVariants", "Product_Key");
            CreateIndex("dbo.ProductCategories", "Category_Key");
            CreateIndex("dbo.ProductCategories", "Product_Key");
            CreateIndex("dbo.Categories", "Name", unique: true);
            CreateIndex("dbo.ProductImages", "Product_Key");
            CreateIndex("dbo.VariantAttributeValues", "AttributeValue_Key");
            CreateIndex("dbo.VariantAttributeValues", "ProductVariant_Key");
            CreateIndex("dbo.ProductVariantImages", "ProductVariant_Key");
            CreateIndex("dbo.UserRoles", new[] { "UserKey", "RoleKey" }, name: "IX_UserAndRole");
            CreateIndex("dbo.Roles", "Name", unique: true);
            AddForeignKey("dbo.AttributeValues", "Attribute_Key", "dbo.Attributes", "Key", cascadeDelete: true);
            AddForeignKey("dbo.AttributeValues", "Value_Key", "dbo.Values", "Key", cascadeDelete: true);
            AddForeignKey("dbo.CartProductVariants", "Cart_Key", "dbo.Carts", "Key", cascadeDelete: true);
            AddForeignKey("dbo.CartProductVariants", "ProductVariant_Key", "dbo.ProductVariants", "Key", cascadeDelete: true);
            AddForeignKey("dbo.Carts", "User_Key", "dbo.Users", "Key", cascadeDelete: true);
            AddForeignKey("dbo.Orders", "User_Key", "dbo.Users", "Key", cascadeDelete: true);
            AddForeignKey("dbo.OrderProductVariants", "Order_Key", "dbo.Orders", "Key", cascadeDelete: true);
            AddForeignKey("dbo.OrderProductVariants", "ProductVariant_Key", "dbo.ProductVariants", "Key", cascadeDelete: true);
            AddForeignKey("dbo.ProductVariants", "Product_Key", "dbo.Products", "Key", cascadeDelete: true);
            AddForeignKey("dbo.VariantAttributeValues", "ProductVariant_Key", "dbo.ProductVariants", "Key", cascadeDelete: true);
            AddForeignKey("dbo.ProductVariantImages", "ProductVariant_Key", "dbo.ProductVariants", "Key", cascadeDelete: true);
            AddForeignKey("dbo.ProductCategories", "Product_Key", "dbo.Products", "Key", cascadeDelete: true);
            AddForeignKey("dbo.ProductImages", "Product_Key", "dbo.Products", "Key", cascadeDelete: true);
            AddForeignKey("dbo.ProductCategories", "Category_Key", "dbo.Categories", "Key", cascadeDelete: true);
            AddForeignKey("dbo.VariantAttributeValues", "AttributeValue_Key", "dbo.AttributeValues", "Key", cascadeDelete: true);
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.VariantAttributeValues", "AttributeValue_Key", "dbo.AttributeValues");
            DropForeignKey("dbo.ProductCategories", "Category_Key", "dbo.Categories");
            DropForeignKey("dbo.ProductImages", "Product_Key", "dbo.Products");
            DropForeignKey("dbo.ProductCategories", "Product_Key", "dbo.Products");
            DropForeignKey("dbo.ProductVariantImages", "ProductVariant_Key", "dbo.ProductVariants");
            DropForeignKey("dbo.VariantAttributeValues", "ProductVariant_Key", "dbo.ProductVariants");
            DropForeignKey("dbo.ProductVariants", "Product_Key", "dbo.Products");
            DropForeignKey("dbo.OrderProductVariants", "ProductVariant_Key", "dbo.ProductVariants");
            DropForeignKey("dbo.OrderProductVariants", "Order_Key", "dbo.Orders");
            DropForeignKey("dbo.Orders", "User_Key", "dbo.Users");
            DropForeignKey("dbo.Carts", "User_Key", "dbo.Users");
            DropForeignKey("dbo.CartProductVariants", "ProductVariant_Key", "dbo.ProductVariants");
            DropForeignKey("dbo.CartProductVariants", "Cart_Key", "dbo.Carts");
            DropForeignKey("dbo.AttributeValues", "Value_Key", "dbo.Values");
            DropForeignKey("dbo.AttributeValues", "Attribute_Key", "dbo.Attributes");
            DropIndex("dbo.Roles", new[] { "Name" });
            DropIndex("dbo.UserRoles", "IX_UserAndRole");
            DropIndex("dbo.ProductVariantImages", new[] { "ProductVariant_Key" });
            DropIndex("dbo.VariantAttributeValues", new[] { "ProductVariant_Key" });
            DropIndex("dbo.VariantAttributeValues", new[] { "AttributeValue_Key" });
            DropIndex("dbo.ProductImages", new[] { "Product_Key" });
            DropIndex("dbo.Categories", new[] { "Name" });
            DropIndex("dbo.ProductCategories", new[] { "Product_Key" });
            DropIndex("dbo.ProductCategories", new[] { "Category_Key" });
            DropIndex("dbo.ProductVariants", new[] { "Product_Key" });
            DropIndex("dbo.OrderProductVariants", new[] { "ProductVariant_Key" });
            DropIndex("dbo.OrderProductVariants", new[] { "Order_Key" });
            DropIndex("dbo.Orders", new[] { "User_Key" });
            DropIndex("dbo.Users", new[] { "Email" });
            DropIndex("dbo.Users", new[] { "Name" });
            DropIndex("dbo.Carts", new[] { "User_Key" });
            DropIndex("dbo.CartProductVariants", new[] { "ProductVariant_Key" });
            DropIndex("dbo.CartProductVariants", new[] { "Cart_Key" });
            DropIndex("dbo.Values", new[] { "Name" });
            DropIndex("dbo.AttributeValues", new[] { "Value_Key" });
            DropIndex("dbo.AttributeValues", new[] { "Attribute_Key" });
            DropIndex("dbo.Attributes", new[] { "Name" });
            AlterColumn("dbo.Roles", "Name", c => c.String());
            AlterColumn("dbo.ProductVariantImages", "ProductVariant_Key", c => c.Guid());
            AlterColumn("dbo.ProductVariantImages", "ImagePath", c => c.String());
            AlterColumn("dbo.VariantAttributeValues", "ProductVariant_Key", c => c.Guid());
            AlterColumn("dbo.VariantAttributeValues", "AttributeValue_Key", c => c.Guid());
            AlterColumn("dbo.ProductImages", "Product_Key", c => c.Guid());
            AlterColumn("dbo.ProductImages", "ImagePath", c => c.String());
            AlterColumn("dbo.Categories", "Name", c => c.String());
            AlterColumn("dbo.ProductCategories", "Product_Key", c => c.Guid());
            AlterColumn("dbo.ProductCategories", "Category_Key", c => c.Guid());
            AlterColumn("dbo.Products", "Name", c => c.String());
            AlterColumn("dbo.ProductVariants", "Product_Key", c => c.Guid());
            AlterColumn("dbo.ProductVariants", "Price", c => c.Single(nullable: false));
            AlterColumn("dbo.OrderProductVariants", "ProductVariant_Key", c => c.Guid());
            AlterColumn("dbo.OrderProductVariants", "Order_Key", c => c.Guid());
            AlterColumn("dbo.Orders", "User_Key", c => c.Guid());
            AlterColumn("dbo.Users", "Salt", c => c.String());
            AlterColumn("dbo.Users", "HashedPassword", c => c.String());
            AlterColumn("dbo.Users", "Email", c => c.String());
            AlterColumn("dbo.Users", "Name", c => c.String());
            AlterColumn("dbo.Carts", "User_Key", c => c.Guid());
            AlterColumn("dbo.CartProductVariants", "ProductVariant_Key", c => c.Guid());
            AlterColumn("dbo.CartProductVariants", "Cart_Key", c => c.Guid());
            AlterColumn("dbo.Values", "Name", c => c.String());
            AlterColumn("dbo.AttributeValues", "Value_Key", c => c.Guid());
            AlterColumn("dbo.AttributeValues", "Attribute_Key", c => c.Guid());
            AlterColumn("dbo.Attributes", "Name", c => c.String());
            CreateIndex("dbo.UserRoles", "RoleKey");
            CreateIndex("dbo.UserRoles", "UserKey");
            CreateIndex("dbo.ProductVariantImages", "ProductVariant_Key");
            CreateIndex("dbo.VariantAttributeValues", "ProductVariant_Key");
            CreateIndex("dbo.VariantAttributeValues", "AttributeValue_Key");
            CreateIndex("dbo.ProductImages", "Product_Key");
            CreateIndex("dbo.ProductCategories", "Product_Key");
            CreateIndex("dbo.ProductCategories", "Category_Key");
            CreateIndex("dbo.ProductVariants", "Product_Key");
            CreateIndex("dbo.OrderProductVariants", "ProductVariant_Key");
            CreateIndex("dbo.OrderProductVariants", "Order_Key");
            CreateIndex("dbo.Orders", "User_Key");
            CreateIndex("dbo.Carts", "User_Key");
            CreateIndex("dbo.CartProductVariants", "ProductVariant_Key");
            CreateIndex("dbo.CartProductVariants", "Cart_Key");
            CreateIndex("dbo.AttributeValues", "Value_Key");
            CreateIndex("dbo.AttributeValues", "Attribute_Key");
            AddForeignKey("dbo.VariantAttributeValues", "AttributeValue_Key", "dbo.AttributeValues", "Key");
            AddForeignKey("dbo.ProductCategories", "Category_Key", "dbo.Categories", "Key");
            AddForeignKey("dbo.ProductImages", "Product_Key", "dbo.Products", "Key");
            AddForeignKey("dbo.ProductCategories", "Product_Key", "dbo.Products", "Key");
            AddForeignKey("dbo.ProductVariantImages", "ProductVariant_Key", "dbo.ProductVariants", "Key");
            AddForeignKey("dbo.VariantAttributeValues", "ProductVariant_Key", "dbo.ProductVariants", "Key");
            AddForeignKey("dbo.ProductVariants", "Product_Key", "dbo.Products", "Key");
            AddForeignKey("dbo.OrderProductVariants", "ProductVariant_Key", "dbo.ProductVariants", "Key");
            AddForeignKey("dbo.OrderProductVariants", "Order_Key", "dbo.Orders", "Key");
            AddForeignKey("dbo.Orders", "User_Key", "dbo.Users", "Key");
            AddForeignKey("dbo.Carts", "User_Key", "dbo.Users", "Key");
            AddForeignKey("dbo.CartProductVariants", "ProductVariant_Key", "dbo.ProductVariants", "Key");
            AddForeignKey("dbo.CartProductVariants", "Cart_Key", "dbo.Carts", "Key");
            AddForeignKey("dbo.AttributeValues", "Value_Key", "dbo.Values", "Key");
            AddForeignKey("dbo.AttributeValues", "Attribute_Key", "dbo.Attributes", "Key");
        }
    }
}
