// <auto-generated />
namespace EarthMarket.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedimageattributesandtablesinproductandproductvarianttable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedimageattributesandtablesinproductandproductvarianttable));
        
        string IMigrationMetadata.Id
        {
            get { return "201812061711597_added image attributes and tables in product and productvariant table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
