// <auto-generated />
namespace EarthMarket.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedattributesforuserandrolesforauthentication : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedattributesforuserandrolesforauthentication));
        
        string IMigrationMetadata.Id
        {
            get { return "201812050548353_added attributes for user and roles for authentication"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
