// <auto-generated />
namespace EarthMarket.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedemailvaliatin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedemailvaliatin));
        
        string IMigrationMetadata.Id
        {
            get { return "201812120759320_added email valiatin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
