// <auto-generated />
namespace EarthMarket.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class orderTotalpriceaddedtoordertable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(orderTotalpriceaddedtoordertable));
        
        string IMigrationMetadata.Id
        {
            get { return "201812110746091_order Total price added to order table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
